### ISSUE TITLE
Missing build/build.js

### ISSUE THREAD

**Issue by rhotacizer** [kdelwat/Onset#5]
When trying to run `npm run build`, npm throws an error because it can't find `build/build.js`:

```
> onset@1.0.0 build .../Onset
> node build/build.js

module.js:471
    throw err;
    ^

Error: Cannot find module '.../Onset/build/build.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! onset@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the onset@1.0.0 build script 'node build/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the onset package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs onset
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls onset
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     .../Onset/npm-debug.log
```

Debug log:
[npm-debug.log.txt](https://github.com/kdelwat/Onset/files/659123/npm-debug.log.txt)

**Comment by kdelwat** [comment]
Sorry, I didn't get a notification for this issue for some reason. I'll check as soon as possible and see what's going on.

**Comment by kdelwat** [comment]
This should be fixed now. Please let me know if you have any more issues :smile:.
